version: '3.9'
services:
  healthkeep-db:
    image: mongo:latest
    restart: always
    container_name: healthkeep-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-data:/data/db